name: Attendance Check Job

on:
  schedule:
    - cron: '30 12 * * *' # 매일 오후 9:30 (KST)
  workflow_dispatch:

jobs:
  attendance-check:
    runs-on: ubuntu-latest
    steps:
      - name: Call Attendance Check API
        run: |
          curl -X GET https://auto-bot-swart.vercel.app/attendance-check
