name: Attendance Check Job

on:
  schedule:
    - cron: '30 12 * * 1-5' # 한국 시간 기준 평일 오후 9:30
  workflow_dispatch:

jobs:
  attendance-check:
    runs-on: ubuntu-latest
    steps:
      - name: Call Attendance Check API
        run: |
          curl -X GET https://auto-bot-swart.vercel.app/attendance-check
