name: Mimo Thread Job

on:
  schedule:
    - cron: '15 20 * * *' # 매일 오전 5:15 (KST)
  workflow_dispatch:

jobs:
  create-mimo-thread:
    runs-on: ubuntu-latest
    steps:
      - name: Call Mimo Thread API
        run: |
          curl -X GET https://auto-bot-swart.vercel.app/create-mimo-thread
