name: Mimo Thread Job

on:
  schedule:
    - cron: '10 11 * * *' # 매일 오후 8:10 KST

jobs:
  create-mimo-thread:
    runs-on: ubuntu-latest
    steps:
      - name: Call Mimo Thread API
        run: |
          curl -X GET https://auto-bot-swart.vercel.app/create-mimo-thread
