name: Mimo Thread Job

on:
  schedule:
    - cron: '50 23 * * *' # 매일 오전 8:50 KST

jobs:
  create-mimo-thread:
    runs-on: ubuntu-latest
    steps:
      - name: Call Mimo Thread API
        run: |
          curl -X GET https://auto-bot-swart.vercel.app/create-mimo-thread
